# This validates the ARM templates, before uploading them to Azure as an artifact

name: Validate ARM Templates CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for changes to the "back-end/arm-templates" folder of the main branch
  push:
    branches: [ main ]
    paths: back-end/arm-templates/**
  pull_request:
    branches: [ main ]
    paths: back-end/arm-templates/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  region: uksouth
  resGroup: CloudResumeChallengeV2

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validation"
  validation:
    name: ARM Template Validations
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Functional verification of ARM templates without connecting to Azure
      - name: ARM Template Toolkit (ARM TTK) Validation
        id: armttkvalidation
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: back-end/arm-templates/main-deploy.json
          
      - name: Display Test Result
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.armttkvalidation.outputs.results)) }}"

      # Logs into Azure with GitHub secret
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUB_CREDENTIALS }}
      
      - name: Validate ARM Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          region: ${{ env.region }}
          template: back-end/arm-templates/main-deploy.json
          deploymentMode: Validate
          parameters: back-end/arm-templates/parameters.json
      
      - name: Upload Template as Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ResumeBackendTemplate
          # A file, directory or wildcard pattern that describes what to upload
          path: back-end/arm-templates/*
          if-no-files-found: error

      # Azure logout
      - name: logout
        run: |
            az logout
        if: always()
