name: Python testing

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: './back-end/arm-templates/azuredeploy.parameters.json'
          prefix: fromjson

      - name: Show python version found in parameters file
        run: |
          echo "The python version is ${{ env.fromjson_parameters_pythonVersion_value }}"
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '${{ env.fromjson_parameters_pythonVersion_value }}'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./back-end/func-app-visitor-api/requirements.txt
    
      # print the current Python version (this will test the matrix)
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./back-end/func-app-visitor-api
        continue-on-error: true
