# This is a basic workflow to help you get started with Actions

name: Test Get Cosmos Account Endpoint+Key

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  extraction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: './back-end/arm-templates/azuredeploy.parameters.json'
          prefix: fromjson
          
      - name: Show output
        run: |
          echo "The resource group is ${{ env.fromjson_parameters_resource_group_value }}"
          echo "The region is ${{ env.fromjson_parameters_cosmos_db_account_name_value }}"
      
      # Logs into Azure with GitHub secret
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUB_CREDENTIALS }}
             
      - name: Get Connection String
        id: connectionstr
        run: |
          MY_STRING=$(az cosmosdb keys list --name sql-cosmos-db-account --resource-group CloudResumeChallenge --type connection-strings)
          MY_STRING="${MY_STRING//$'\n'/''}"
          MY_STRING="${MY_STRING//$'\r'/''}"
          echo "::set-output name=value::$MY_STRING"
          
      - name: Output Connection String
        run: |
          echo "${{ steps.connectionstr.outputs.value }}"

      # Azure logout
      - name: logout
        run: |
            az logout
        if: always()
