name: Python testing

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: './back-end/arm-templates/azuredeploy.parameters.json'
          prefix: fromjson

      - name: Show python version found in parameters file
        run: |
          echo "The python version is ${{ env.fromjson_parameters_pythonVersion_value }}"
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '${{ env.fromjson_parameters_pythonVersion_value }}'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./back-end/func-app-visitor-api/requirements.txt
    
      # print the current Python version (this will test the matrix)
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./back-end/func-app-visitor-api --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./back-end/func-app-visitor-api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Save date to Env variable
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Test with pytest
        run: pytest --junitxml=back-end/pytest-results/test-results-${{ env.MY_DATE }}-${{ matrix.python-version }}.xml
        
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ env.MY_DATE }}-${{ matrix.python-version }}
          path: back-end/pytest-results/test-results-${{ env.MY_DATE }}-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
