# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'back-end/arm-templates/azuredeploy.parameters.json'
          prefix: test
      - name: Show output
        run: |
          echo "The ${{ env.test_parameters_0 }} is ${{ env.test_parameters_resource_group_value }}"
          echo "The ${{ env.test_parameters_1 }} is ${{ env.test_parameters_storage_account_name_value }}"
          echo "The ${{ env.test_parameters_2 }} is ${{ env.test_parameters_cdn_profile_name_value }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo This is the end of the script
          echo *****************************
